-- MySQL Script generated by MySQL Workbench
-- Mon Oct 18 20:15:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `CAPITULO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CAPITULO` ;

CREATE TABLE IF NOT EXISTS `CAPITULO` (
  `LIVRO_ID` INT NOT NULL,
  `Numeracao` INT NOT NULL,
  `Titulo` VARCHAR(60) NULL,
  `QT_Secoes` INT NOT NULL,
  PRIMARY KEY (`LIVRO_ID`, `Numeracao`),
  CONSTRAINT `fk_Chapter_Book`
    FOREIGN KEY (`LIVRO_ID`)
    REFERENCES `LIVRO` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Chapter_Book_idx` ON `CAPITULO` (`LIVRO_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EMLEITURA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMLEITURA` ;

CREATE TABLE IF NOT EXISTS `EMLEITURA` (
  `LIVRO_ID` INT NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  `CapAtual` INT NOT NULL,
  `SecAtual` INT NOT NULL,
  CONSTRAINT `fk_Atual_User`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `USUARIO` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Atuak_Book`
    FOREIGN KEY (`LIVRO_ID`)
    REFERENCES `LIVRO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Atual_User_idx` ON `EMLEITURA` (`USUARIO_ID` ASC) VISIBLE;

CREATE INDEX `fk_Atual_Book_idx` ON `EMLEITURA` (`LIVRO_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LIVRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LIVRO` ;

CREATE TABLE IF NOT EXISTS `LIVRO` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Autor` VARCHAR(45) NULL,
  `Lancamento` DATE NULL,
  `Sinopse` TINYTEXT NULL,
  `Categoria` VARCHAR(20) NOT NULL,
  `QT_Pag` INT NULL,
  `QT_Cap` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `LIVRO` (`ID` ASC) VISIBLE;

CREATE UNIQUE INDEX `Nome_UNIQUE` ON `LIVRO` (`Nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PARAGRAFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PARAGRAFO` ;

CREATE TABLE IF NOT EXISTS `PARAGRAFO` (
  `CAP_ID` INT NOT NULL,
  `LIVRO_ID` INT NOT NULL,
  `Numeracao` INT NOT NULL,
  `Conteudo` LONGTEXT NOT NULL,
  PRIMARY KEY (`CAP_ID`, `LIVRO_ID`, `Numeracao`),
  CONSTRAINT `fk_Paragraph_Chapter`
    FOREIGN KEY (`CAP_ID` , `LIVRO_ID`)
    REFERENCES `CAPITULO` (`Numeracao` , `LIVRO_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Paragraph_Chapter_idx` ON `PARAGRAFO` (`CAP_ID` ASC, `LIVRO_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIO` ;

CREATE TABLE IF NOT EXISTS `USUARIO` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Senha` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `USUARIO` (`ID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
